spring:
  cloud:
    openfeign:
      client:
        config:
          pets:
            connectTimeout: 5000 # Connection timeout in milliseconds
            readTimeout: 10000   # Read timeout in milliseconds
            loggerLevel: full
            errorDecoder: org.example.config.PetErrorDecoder
pets:
  name: pets
  url: localhost:8085